version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2024.01.2

    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run:
          name: Run Tests
          command: |
            PYTHONPATH=. py.test --verbose -s || true
      - run: make docker_build

workflows:
  basic:
    jobs:
      - build-and-test