version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10 

    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test

workflows:
  basic:
    jobs:
      - build-and-test
